# Generated by Django 3.2.8 on 2021-11-09 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20211109_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(blank=True, default=None, max_length=8, verbose_name='Post code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, default=1990, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='Year of birth'),
            preserve_default=False,
        ),
    ]
