# Generated by Django 4.0.6 on 2022-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0002_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpair",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
