# Generated by Django 3.2.8 on 2021-11-10 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20211109_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='Year of birth'),
        ),
    ]
