# Generated by Django 4.0.6 on 2023-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userpair_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postcode_changes',
            field=models.IntegerField(default=3),
        ),
    ]
