# Generated by Django 3.2.8 on 2021-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20211110_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='accounts/avatars/'),
        ),
    ]
