# Generated by Django 3.2.8 on 2021-11-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_customuser_avatar'),
        ('userauth', '0005_userrequest'),
    ]

    operations = [
    ]
