# Generated by Django 4.0.6 on 2022-11-09 16:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poll.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('question', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('options', models.JSONField(validators=[poll.models.validate_poll_options])),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed', models.BooleanField(default=False)),
                ('invalid_option', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.basepoll')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoicePoll',
            fields=[
                ('basepoll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.basepoll')),
            ],
            bases=('poll.basepoll',),
        ),
        migrations.CreateModel(
            name='MultipleVote',
            fields=[
                ('basevote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.basevote')),
                ('choice', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            bases=('poll.basevote',),
        ),
        migrations.CreateModel(
            name='SingleChoicePoll',
            fields=[
                ('basepoll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.basepoll')),
            ],
            bases=('poll.basepoll',),
        ),
        migrations.CreateModel(
            name='SingleVote',
            fields=[
                ('basevote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.basevote')),
                ('choice', models.IntegerField(default=None, null=True)),
            ],
            bases=('poll.basevote',),
        ),
    ]
