# Generated by Django 4.0.6 on 2022-11-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepoll',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='basepoll',
            name='created_by',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basepoll',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
