# Generated by Django 4.0.6 on 2022-12-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_basepoll_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepoll',
            name='when_closed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
