# Generated by Django 4.0.6 on 2022-11-09 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(default='', max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='messages/images/')),
                ('file', models.FileField(blank=True, upload_to='messages/files/')),
                ('snippet', models.CharField(default='', max_length=2000)),
                ('hidden', models.BooleanField(default=False)),
                ('context_bool', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat')),
                ('context_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.action')),
            ],
        ),
    ]
