# Generated by Django 4.0.6 on 2022-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden_reason',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
