# Generated by Django 4.0.6 on 2022-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
