# Generated by Django 4.2.3 on 2024-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_resource_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="location_exact",
            field=models.BooleanField(default=True),
        ),
    ]
