# Generated by Django 4.2.3 on 2024-04-29 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import messaging.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0006_alter_message_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemixContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=2000)),
                (
                    "chat",
                    models.ForeignKey(
                        default=messaging.models.new_chat,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="messaging.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemixBackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("image", models.ImageField(upload_to="remix/images/")),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="remix.remixcontainer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Remix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("scene", models.JSONField()),
                (
                    "background_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="remix.remixbackgroundimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
