# Generated by Django 4.2.3 on 2024-05-03 12:54

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0006_alter_message_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemixIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=2000)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        default=messaging.models.new_chat,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="messaging.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemixBackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("image", models.ImageField(upload_to="remix/backgrounds/")),
                ("initial_image", models.BooleanField(default=False)),
                (
                    "from_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="messaging.message",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_images",
                        to="remix.remixidea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Remix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("scene", models.JSONField(null=True)),
                (
                    "snapshot",
                    models.ImageField(blank=True, upload_to="remix/snapshots/"),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_image",
                        to="remix.remixbackgroundimage",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remixes",
                        to="remix.remixidea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
