# Generated by Django 4.2.3 on 2024-04-29 17:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import messaging.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_alter_message_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("remix", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remix",
            name="snapshot",
            field=models.ImageField(blank=True, upload_to="remix/snapshots/"),
        ),
        migrations.AlterField(
            model_name="remixbackgroundimage",
            name="image",
            field=models.ImageField(upload_to="remix/backgrounds/"),
        ),
        migrations.CreateModel(
            name="RemixIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=2000)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        default=messaging.models.new_chat,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="messaging.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="remixbackgroundimage",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="remix.remixidea"
            ),
        ),
        migrations.DeleteModel(
            name="RemixContainer",
        ),
    ]
