# Generated by Django 4.2.3 on 2024-05-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remix",
            name="from_remix",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="remix.remix",
            ),
        ),
    ]
