# Generated by Django 4.2.3 on 2024-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0002_remix_snapshot_alter_remixbackgroundimage_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remixbackgroundimage",
            old_name="container",
            new_name="idea",
        ),
    ]
