# Generated by Django 4.2.3 on 2024-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0004_alter_remix_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remix",
            name="scene",
            field=models.JSONField(blank=True),
        ),
    ]
