# Generated by Django 4.2.3 on 2024-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0005_alter_remix_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remix",
            name="scene",
            field=models.JSONField(null=True),
        ),
    ]
