# Generated by Django 4.2.3 on 2024-05-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0006_alter_remix_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="remix",
            name="idea",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideas",
                to="remix.remixidea",
            ),
            preserve_default=False,
        ),
    ]
