# Generated by Django 4.2.3 on 2024-05-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0007_remix_idea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remix",
            name="idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remixes",
                to="remix.remixidea",
            ),
        ),
    ]
