# Generated by Django 4.2.3 on 2024-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0008_alter_remix_idea"),
    ]

    operations = [
        migrations.AddField(
            model_name="remixbackgroundimage",
            name="initial_image",
            field=models.BooleanField(default=False),
        ),
    ]
