# Generated by Django 4.2.3 on 2024-05-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_alter_message_text"),
        ("remix", "0009_remixbackgroundimage_initial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="remixbackgroundimage",
            name="from_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="messaging.message",
            ),
        ),
    ]
