# Generated by Django 4.2.3 on 2024-05-03 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("remix", "0010_remixbackgroundimage_from_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="remix",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
