# Generated by Django 4.0.6 on 2023-10-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('river', '0006_alter_river_current_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('stage_name', models.CharField(choices=[('plan', 'Plan'), ('act', 'Act')], max_length=8)),
                ('topic', models.CharField(max_length=32)),
                ('done', models.BooleanField(default=False)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='river.river')),
            ],
        ),
    ]
