# Generated by Django 4.2.3 on 2023-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    models.OrderBy(models.F("due"), nulls_last=True),
                    models.OrderBy(models.F("created_at")),
                ]
            },
        ),
    ]
