# Generated by Django 4.0.6 on 2023-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_task_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
