# Generated by Django 4.0.6 on 2022-12-07 13:31

from django.db import migrations, models
import django.db.models.deletion
import river.models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_message_text'),
        ('poll', '0002_initial'),
        ('river', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envisionstage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='envisionstage',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='reflectstage',
            name='chat',
        ),
        migrations.AddField(
            model_name='envisionstage',
            name='general_chat',
            field=models.ForeignKey(default=river.models.new_chat, on_delete=django.db.models.deletion.SET_DEFAULT, to='messaging.chat'),
        ),
        migrations.AddField(
            model_name='envisionstage',
            name='general_poll',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.singlechoicepoll'),
        ),
        migrations.AddField(
            model_name='reflectstage',
            name='general_chat',
            field=models.ForeignKey(default=river.models.new_chat, on_delete=django.db.models.deletion.SET_DEFAULT, to='messaging.chat'),
        ),
    ]
