# Generated by Django 4.0.6 on 2022-12-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0003_basepoll_passed"),
        ("river", "0003_remove_envisionstage_chat_remove_envisionstage_poll_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectstage",
            name="general_poll",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="poll.multiplechoicepoll",
            ),
        ),
    ]
