# Generated by Django 4.2.3 on 2023-12-20 19:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0006_alter_river_current_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="river",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
