# Generated by Django 4.2.3 on 2024-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0007_river_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="river",
            name="location_exact",
            field=models.BooleanField(default=True),
        ),
    ]
