# Generated by Django 4.2.3 on 2024-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0003_area_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="zoom",
            field=models.IntegerField(default=12),
        ),
    ]
