# Generated by Django 4.2.3 on 2024-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("area", "0005_alter_area_zoom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
