# Generated by Django 3.2.8 on 2021-10-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['display_name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='anonymous', help_text='Will be shown alongside entries', max_length=30, verbose_name='Display name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(default='lobwqy', max_length=8, verbose_name='Post code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_birth',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='Year of birth'),
            preserve_default=False,
        ),
    ]
